name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 00 12 * * * #8am EDT
    - cron : 00 10 * * 1-5 #6pm EDT
    - cron : 26 15 * * * #1126am EDT

jobs:
  run-postman-tests:
    runs-on: ununtu-latest

    steps:
      
       - name: Checkout the code
         uses: actions/checkout@v5.0.0
          
       - name: Install Nodejs and npm
         uses: actions/setup-node@v5.0.0
         with:
           node-version: '22'

       - name: Install Newman and Html-extra globally
         run: |
              npm install -g newman
              npm install -g newman-reporter-htmlextra

       - name: Run the Postman Collection with newman
         run: |
              newman run 'Inwarranty-flow Collection.postman_collection.json' \
              -e QA.postman_environment.json \
              -d testdata.csv \
              -r cli,htmlextra
