name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 00 12 * * * #8am EDT
    - cron : 00 10 * * 1-5 #6pm EDT
    - cron : 30 15 * * * #1126am EDT

jobs:
  run-postman-tests:
    runs-on: ec2 github runner

    steps:
      
       - name: Checkout the code
         uses: actions/checkout@v5.0.0
          
       - name: Install Nodejs and npm
         uses: actions/setup-node@v5.0.0
         with:
           node-version: '22'

       - name: Install Newman and Html-extra globally
         run: |
              npm install -g newman
              npm install -g newman-reporter-htmlextra

       - name: Run the Postman Collection with newman
         run: |
              newman run 'Inwarranty-flow Collection.postman_collection.json' \
              -e QA.postman_environment.json \
              -d testdata.csv \
              -r cli,htmlextra \
              --reporter-htmlextra-export ./newman/index.html

       - name: Newman Report
         if: always() #ensure that the archive executed irrespective whether the previous steps has failed or not!
         uses: actions/upload-artifact@v4.6.2
         with:
           name: Newman Report
           path: newman/*.html

       - name: Creating github page branch
         if: always()
         uses: peaceiris/actions-gh-pages@v4.0.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: newman/

           
       - name: Send Email Notifications
         if: always()
         uses: dawidd6/action-send-mail@v6
         with:
           server_address: smtp.gmail.com
           server_port: 465
           username: ${{ secrets.EMAIL_USERNAME }}
           password: ${{ secrets.EMAIL_PASSWORD }}
           subject: Phoenix Inwarranty Flow Test Execution Notification
           to: ojhaankit.116@gmail.com
           from: ${{ secrets.EMAIL_USERNAME }}
           body: |
                 Hi,
                 Phoenix Inwarranty Flow Tests has been executed. The Report has been published and the URL is: https://ojhaankit116.github.io/Phoenix-Inwarranty-Flow/
